### ISSUE TITLE
xdb编译有问题

### ISSUE THREAD

**Issue by nihaoqingtuan** [PaddlePaddle/PaddleDTX#147]

**Comment by nihaoqingtuan** [comment]
go mod tidy:
go: finding module for package github.com/xuperchain/crypto/core/utils
github.com/PaddlePaddle/PaddleDTX/xdb/blockchain/xchain imports
        github.com/xuperchain/xuper-sdk-go/contract tested by
        github.com/xuperchain/xuper-sdk-go/contract.test imports
        github.com/xuperchain/xuper-sdk-go/transfer imports
        github.com/xuperchain/crypto/core/utils: module github.com/xuperchain/crypto@latest found (v0.0.0-20211224062819-eca101aeda3f), but does not contain package github.com/xuperchain/crypto/core/utils

**Comment by hongyanwang** [comment]
拉最新代码再试试

**Comment by nihaoqingtuan** [comment]
可以了。但是现在有个新问题：我重新拉取一份新代码后没有make，跟着快速安装文档[https://paddledtx.readthedocs.io/zh_CN/latest/quickstart/quickstart/](url) 启动网络报错：

> 
$ sh network_up.sh start
==========> Xchain network start ...
[+] Running 2/3
 ⠿ Container xchain3.node.com  Running                                                                                                                                                     0.0s
 ⠿ Container xchain2.node.com  Running                                                                                                                                                     0.0s
 ⠹ Container xchain1.node.com  Starting                                                                                                                                                    0.2s
Error response from daemon: driver failed programming external connectivity on endpoint xchain1.node.com (c41ab9928bd712348ead8a82a7ff4ad0df6d275a49f9e2a76ca79787fa63233e):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i br-ae601afe3ddc -o br-ae601afe3ddc -p tcp -d 172.31.1.3 --dport 37101 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1))

>

**Comment by nihaoqingtuan** [comment]
请问是有什么问题？

**Comment by nihaoqingtuan** [comment]
$ docker -v
Docker version 20.10.0, build 7287ab3
$ docker-compose version
Docker Compose version v2.10.2

**Comment by nihaoqingtuan** [comment]
我重启docker网络后显示如下：

> 
$ sh network_up.sh start
==========> Xchain network start ...
[+] Running 3/3
 ⠿ Container xchain2.node.com  Started                                                                                                                                                     1.2s
 ⠿ Container xchain3.node.com  Started                                                                                                                                                     1.3s
 ⠿ Container xchain1.node.com  Started                                                                                                                                                     1.4s
==========> Xchain network starts successfully !
==========> Install paddlempc contract start ...
Unable to find image 'golang:1.13.4' locally
1.13.4: Pulling from library/golang
16ea0e8c8879: Pull complete 
50024b0106d5: Pull complete 
ff95660c6937: Pull complete 
9c7d0e5c0bc2: Pull complete 
2a19d2e6789c: Pull complete 
bd9cab5aeb31: Pull complete 
0ed236c95063: Pull complete 
Digest: sha256:f9de064473fb30c66bc0d2ddf2cf9a4a9bd38cbd2c5e59ce3bdf8af7b8747a57
Status: Downloaded newer image for golang:1.13.4
go: github.com/PaddlePaddle/PaddleDTX/crypto@v0.0.0-20220705024525-b5b6c6a3ad76: Get https://goproxy.cn/github.com/%21paddle%21paddle/%21paddle%21d%21t%21x/crypto/@v/v0.0.0-20220705024525-b5b6c6a3ad76.mod: dial tcp 163.181.42.229:443: i/o timeout
lstat /home/10336999@zte.intra/PaddleDTX/PaddleDTX/testdatatmp/blockchain/xchain/contract: no such file or directory
user address eFHH6ovPcG6eMszLB4DxFWeY3EBPZ9Hrb ...
create contract account successfully, contract response: 
        {
            "pm": {
                "rule": 1,
                "acceptValue": 1.0
            },
            "aksWeight": {
                "eFHH6ovPcG6eMszLB4DxFWeY3EBPZ9Hrb": 1.0
            }
        }
        
The gas you cousume is: 1000
The fee you pay is: 1000
Tx id: 96cea56052ac2df8b1cc6c62dcd06a382656f5b065e1fdb8bc22b11665ff4fb3
 ...unt name: XC1111111111111112@xuper
 ...sfer amount to contract account successfully, add1c898bff5e45a70b2aefbd72b54b2eaccfc187386cc305ea8961645d5d257
==========> Install paddlempc contract successfully ! 
==========> Decentralized storage network start ...
[+] Running 0/6
 ⠿ storage2 Error                                                                                                                                                                         10.3s
 ⠿ storage3 Error                                                                                                                                                                         10.3s
 ⠿ dataowner1 Error                                                                                                                                                                       10.3s
 ⠿ dataowner2 Error                                                                                                                                                                       10.3s
 ⠿ dataowner3 Error                                                                                                                                                                       10.3s
 ⠿ storage1 Error                                                                                                                                                                         10.3s
Error response from daemon: Get https://registry.baidubce.com/v2/: net/http: TLS handshake timeout
Error: No such object: dataowner1.node.com
==========> Decentralized storage network start error ...

**Comment by hongyanwang** [comment]
首先运行build_image.sh打包存储服务的镜像，其次确保你的机器可以访问github

**Comment by nihaoqingtuan** [comment]
我的机子是可以连github的。我运行了，但是报错：

> 
$ ./build_image.sh
go: github.com/Joker/hpp@v1.0.0: Get https://goproxy.cn/github.com/%21joker/hpp/@v/v1.0.0.mod: dial tcp 163.181.42.230:443: i/o timeout
Error: No such image: registry.baidubce.com/paddledtx/xdb-dataowner:2.1
Error: No such image: registry.baidubce.com/paddledtx/xdb-storage:2.1
Sending build context to Docker daemon  1.244MB
Step 1/10 : FROM ubuntu:18.04
 ---> 3941d3b032a8
Step 2/10 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 47230036515f
Step 3/10 : RUN mkdir -p /home
 ---> Using cache
 ---> e6b9993f176e
Step 4/10 : RUN mkdir /home/data
 ---> Using cache
 ---> 8f5f0c07964c
Step 5/10 : WORKDIR /home
 ---> Using cache
 ---> 47f564731a99
Step 6/10 : COPY ./xdb .
COPY failed: file not found in build context or excluded by .dockerignore: stat xdb: file does not exist
Error response from daemon: No such image: registry.baidubce.com/paddledtx/xdb-dataowner:2.1

**Comment by hongyanwang** [comment]
主要错误为：go: github.com/Joker/hpp@v1.0.0: Get https://goproxy.cn/github.com/%21joker/hpp/@v/v1.0.0.mod: dial tcp 163.181.42.230:443: i/o timeout，拉取依赖包超时了。估计是机器环境问题，可以网上搜一下解决办法

**Comment by hongyanwang** [comment]
我建议你先修复这个问题，因为启动网络(network_up.sh start)的时候也有这个问题：go: github.com/PaddlePaddle/PaddleDTX/crypto@v0.0.0-20220705024525-b5b6c6a3ad76: Get https://goproxy.cn/github.com/%21paddle%21paddle/%21paddle%21d%21t%21x/crypto/@v/v0.0.0-20220705024525-b5b6c6a3ad76.mod: dial tcp 163.181.42.229:443: i/o timeout
