### ISSUE TITLE
XuperDB源代码编译安装在XuperDB这里碰到了问题

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleDTX#30]
首先Docker快速案例是可以跑通的。

但是源代码编译安装碰到了问题，在AIStudio的BML环境下：
按照手册源码编译安装，执行到部署 XuperDB 启动数据存储节点这块，
执行命令：
./xdb -c conf/config-storage.toml > storage.log后报错：

ERRO[0000] app exit                                      error="missing log config"

按照手册里修改成如下配置文件
```
# vim conf/config-dataowner.toml
# 
listenAddress = ":8123"
publicAddress = "127.0.0.1:8123"

# genkey创建的私钥, 对账户使用不熟悉的话建议使用默认账户
privateKey = "5572e2fa0c259fe798e5580884359a4a6ac938cfff62d027b90f2bac3eceef79"

[dataOwner.blockchain]
    [dataOwner.blockchain.xchain]
        # 助记词为用户安装合约过程中创建的区块链账户，取值./ukeys/mnemonic
        mnemonic = "充 雄 孔 坝 低 狠 争 短 摸 拜 晨 造"
        contractName = "paddlempc"
        contractAccount = "XC1234567890123456@xuper"
        chainAddress = "127.0.0.1:37101"
        chainName = "xuper"
```
则执行后会报错：

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0xa8bb81]

goroutine 1 [running]:
github.com/spf13/viper.(*Viper).AllKeys(0x0)
	/home/aistudio/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:1824 +0xa1
github.com/spf13/viper.(*Viper).AllSettings(0x0)
	/home/aistudio/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:1904 +0x45
github.com/spf13/viper.(*Viper).Unmarshal(0xc0005f1cd8, {0x1165a40, 0xc000a4a8e0}, {0x0, 0x0, 0x0})
	/home/aistudio/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:908 +0x32
github.com/PaddlePaddle/PaddleDTX/xdb/config.InitConfig({0x7fff43948c94, 0x12})
	/home/aistudio/PaddleDTX/xdb/config/config.go:87 +0x1aa
main.init.0()
	/home/aistudio/PaddleDTX/xdb/main.go:63 +0xbe
```
因为对go语言报错实在看不懂，所以不知道该怎么查找和纠错。

 我的项目已经公开，放在这里：https://aistudio.baidu.com/aistudio/projectdetail/3255074
go version go1.17.5 linux/amd64
GNU Make 4.1

**Comment by MyYuan** [comment]
报错missing log config，代表conf/config-storage.toml配置中的log配置为空，参考https://github.com/PaddlePaddle/PaddleDTX/blob/master/xdb/conf/config-storage.toml 添加配置，重启即可

**Comment by skywalk163** [comment]
加上log后，报错：
2021/12/24 23:33:56 Config yamlFile get error #open ./conf/sdk.yaml: no such file or directory
2021/12/24 23:33:56 GetConfig: &{10.144.94.18:8848 {false false 10 XBbhR82cB6PvaLJs3D4uB9f12bhmKkHeX TYyA3y8wdFZyzExtcbRNVd7ZZ2XXcfjdw} 100 xchain}

**Comment by skywalk163** [comment]
另一台系统修改了配置之后，会跟前面一样的go报错：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x468a8a1]

goroutine 1 [running]:
github.com/spf13/viper.(*Viper).AllKeys(0x0)

**Comment by MyYuan** [comment]
错误输出 /home/aistudio/PaddleDTX/xdb/config/config.go:87 +0x1aa ，代表log没有配置，你加上log之后，服务仍未启动成功，则可以tail -f logs/server.log查看详细的报错日志，通过详细错误日志，可以看出你的配置问题；

**Comment by skywalk163** [comment]
最新的server.log日志是：

`time="2021-12-27T21:30:42+08:00" level=info msg="monitor initialize..." answer-interval=10m0s monitor=challenging request-interval=1h7m0s
time="2021-12-27T21:30:42+08:00" level=info msg="monitor initialize..." fileclear-interval=24h0m0s fileretain-interval=168h0m0s heartbeat-interval=1m0s monitor=nodemaintainer
time="2021-12-27T21:30:42+08:00" level=error msg="failed to register node automatically"
time="2021-12-27T21:30:42+08:00" level=error msg="app exit" error="failed to register node automatically: {\"code\":\"XDAT0001\",\"message\":\"failed to PreInvokeNativeContract: rpc error: code = Unknown desc = Err:500-50001-unknown error+no enough money(UTXO) to start this transaction\"}"`

看报错是不是需要较大的内存？ 

我是全部照抄的手册配置，地址：https://paddledtx.readthedocs.io/zh_CN/latest/quickstart/compile-install.html
我想确认下privateKey = "5572e2fa0c259fe798e5580884359a4a6ac938cfff62d027b90f2bac3eceef79" 可以直接用文档里面的吗？

**Comment by skywalk163** [comment]
哇，把私钥和自己的助记词输入后，服务应该是起来了。
`2021/12/27 21:48:00 Config yamlFile get error #open ./conf/sdk.yaml: no such file or directory
2021/12/27 21:48:00 GetConfig: &{10.144.94.18:8848 {false false 10 XBbhR82cB6PvaLJs3D4uB9f12bhmKkHeX TYyA3y8wdFZyzExtcbRNVd7ZZ2XXcfjdw} 100 xchain}
2021/12/27 21:48:00 Gas will cost: 1170
2021/12/27 21:48:00 contract response: added
Now listening on: http://localhost:8122
Application started. Press CTRL+C to shut down.
2021/12/27 21:48:00 contract response: {"ID":"YWNhNmI0MzkyMDgzOGVhNGE0MDY2NzlhZTI4YWE3ZDJiZmQzMThkYjljNjg0NjYyZDg0Y2MxOGU4ZDc3N2ZiM2Y4NjQ5YTA4N2E4ZGEzYjhmOThmNjgwNmJkNGM3ZDRmOGIyNzQyYTJhMzRjYTI0ZWRmMDk3Nzg0NDdhNTYxNDk=","Name":"storageNode1","Address":"127.0.0.1:8122","Online":true,"RegTime":1640612880351143962,"UpdateAt":1640612880351143962}
2021/12/27 21:48:00 Gas will cost: 1`

美中不足是还有个报错：
`2021/12/27 21:48:00 Config yamlFile get error #open ./conf/sdk.yaml: no such file or directory`

**Comment by MyYuan** [comment]
Config yamlFile get error #open ./conf/sdk.yaml: no such file or directory 该错误是依赖模块提示，可参考https://github.com/xuperchain/xuper-sdk-go 配置，当前项目如果不配置不影响服务正常使用；
