### ISSUE TITLE
手册创建命名空间命令参数出错

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleDTX#32]
## 创建命名空间报错
手册位置：https://paddledtx.readthedocs.io/zh_CN/latest/quickstart/client.html
操作XuperDB ，创建命名空间这步：

在AIStudio BML notebook环境中，使用的命令为：
!cd ~/PaddleDTX/xdb/output &&  ./xdb-cli files addns  --host http://127.0.0.1:8122 -k eae7344064e1d5b53af6da1a23407b1e7e265d15eaf0442c476e3caac3003406 -n paddlempc  -r 2
报错信息为：
```
err：{"code":"XDAT0004","message":"from xdb api: request url not found"}
```
调试的时候百思不得其解，甚至一度怀疑端口监听到ipv6地址了。但是查看前面开服务的时候，已经测试连接，输出状态信息了。

后来仔细看，发现是连通数据持有节点，而8122端口是数据存储节点，原来文档上面写错端口号了。

修改命令端口号到8123，搞定！

!cd ~/PaddleDTX/xdb/output &&  ./xdb-cli files addns  --host http://127.0.0.1:8123 -k eae7344064e1d5b53af6da1a23407b1e7e265d15eaf0442c476e3caac3003406 -n paddlempc  -r 2

**Comment by gaoweibupt** [comment]
搭建文档里面配置给的端口号数据持有节点是8123，客户端命令 Demo 用的8122，出现了不一致问题，这个会统一验证并修复

**Comment by skywalk163** [comment]
哦哦，好的哦
