### ISSUE TITLE
xdb部署和性能问题

### ISSUE THREAD

**Issue by luoweb** [PaddlePaddle/PaddleDTX#53]
PaddleDTX中的xdb支持跨广域网部署能力吗？有相关的性能测试数据吗？

**Comment by MyYuan** [comment]
支持，可以将存储节点部署在广域网，将数据持有节点部署在能访问广域网的内网即可；
关于文件的存取性能与节点服务器配置有关，我们的性能测试如TPS、平均响应时间等，其在xchain、fabric网络下均表现良好；

**Comment by luoweb** [comment]
有具体的实际部署的测试数据吗？

**Comment by MyYuan** [comment]
基础环境：1个数据持有节点，5个存储节点，centos 6.10
